Repository robbevp/feed-reader, pull requests merged in 2025-02, with the labels that each got.

#614 Fix entries controller responding with 404 when logged out/unauthorized
  app/controllers/entries_controller.rb
Labels: bug

#627 Setup service group for rails server and vite dev server
  flake.nix
Labels: chore

#625 Redirect user to path before sign in
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  test/controllers/entries_controller_test.rb
  test/controllers/sessions_controller_test.rb
Labels: enhancement

#624 Allow user to create longer session
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/views/sessions/new.html.erb
  test/controllers/sessions_controller_test.rb
  test/test_helper.rb
Labels: enhancement

#630 Allow user to switch to dark mode (with system/browser settings)
  app/assets/entrypoints/entry-body.css
  app/assets/styles/base/index.css
  app/assets/styles/base/theme.css
  app/assets/styles/components/entry-nav.css
Labels: enhancement
