Repository robbevp/feed-reader, pull requests merged in 2025-08, with the labels that each got.

#778 Update config for postfix
  module.nix
Labels: chore

#779 Add workaround for hovering in mobile FF
  app/assets/styles/components/entry-nav.css
Labels: bug

#790 Fix format of postfix settings
  module.nix
Labels: bug

#793 Rename `unprocessable_entity` to `unprocessable_content`
  app/controllers/passwords_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/subscriptions_controller.rb
  app/controllers/users_controller.rb
  test/controllers/passwords_controller_test.rb
  test/controllers/sessions_controller_test.rb
  test/controllers/subscriptions_controller_test.rb
  test/controllers/users_controller_test.rb
Labels: chore

#794 Show reading progress on entry page
  app/assets/components/entry_reader_element.js
  app/assets/components/resize_iframe.js
  app/assets/entrypoints/application.js
  app/assets/helpers/throttle.js
  app/assets/styles/base/theme.css
  app/assets/styles/components/entries.css
  app/components/entry_component.html.erb
  config/locales/en.yml
Labels: enhancement

#804 Show last page instead of erroring when going past page limit
  config/initializers/pagy.rb
Labels: enhancement

#604 Handle errors in fetching RSS feeds more gracefully
  app/assets/images/icons/clock.svg
  app/assets/images/icons/exclamation-triangle.svg
  app/assets/images/icons/x-mark.svg
  app/components/subscription_status_component.html.erb
  app/components/subscription_status_component.rb
  app/jobs/refresh_rss_feed_job.rb
  app/jobs/refresh_rss_feeds_job.rb
  app/models/rss_feed.rb
  app/views/subscriptions/index.html.erb
  app/views/subscriptions/show.html.erb
  config/locales/en.yml
  db/migrate/20250127142830_add_last_error_to_rss_feed.rb
  db/schema.rb
  test/components/subscription_status_component_test.rb
  test/factories/rss_feeds.rb
  test/jobs/refresh_rss_feeds_job_test.rb
  test/models/rss_feed_test.rb
Labels: enhancement

#809 Handle feeds that can't be parsed
  app/models/rss_feed.rb
  config/locales/en.yml
  test/models/rss_feed_test.rb
Labels: enhancement
