Repository robbevp/feed-reader, pull requests merged in 2025-01, with the labels that each got.

#579 Discard job on `Errno::ENETUNREACH`
  app/jobs/refresh_rss_feed_job.rb
Labels: bug

#605 Make sure CI gets executed when a PR is created
  .github/workflows/ci.yml
Labels: chore

#597 Add subscription name to entry show page
  app/views/entries/show.html.erb
  config/locales/en.yml
Labels: enhancement

#603 Use Addressable to heuristically parse invalid URLs and normalize them
  Gemfile
  Gemfile.lock
  app/models/entry.rb
  test/models/entry_test.rb
Labels: bug

#596 Allow marking every entry in a subscription as read
  app/controllers/subscriptions_controller.rb
  app/models/subscription.rb
  app/policies/subscription_policy.rb
  app/views/subscriptions/show.html.erb
  config/locales/en.yml
  config/routes.rb
  test/controllers/subscriptions_controller_test.rb
Labels: enhancement

#595 Make entry show an icon and add icon link to original page
  Gemfile
  Gemfile.lock
  app/assets/images/icons/arrow-top-right-on-square.svg
  app/assets/images/icons/eye.svg
  app/assets/styles/base/index.css
  app/views/entries/index.html.erb
  app/views/subscriptions/show.html.erb
  config/initializers/inline_svg.rb
  gemset.nix
  lib/inline_svg/vite_file_loader.rb
Labels: enhancement

#607 Style main navigation/actions on entry page
  app/assets/images/icons/arrow-left.svg
  app/assets/images/icons/arrow-right.svg
  app/assets/styles/application.css
  app/assets/styles/base/index.css
  app/assets/styles/base/theme.css
  app/assets/styles/components/entries.css
  app/assets/styles/components/entry-nav.css
  app/assets/styles/components/icon.css
  app/views/entries/show.html.erb
  config/locales/en.yml
Labels: enhancement

#609 Only show link to url if present
  app/views/entries/index.html.erb
Labels: bug
